project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  pdf: default
  typst: 
    columns: 2
    output-file: caminatas-aleatorias-2c.pdf

  # (other formats)
  # pdf: default

execute:
  freeze: true



